import { Experience } from './store';

export const mockExperiences: Experience[] = [
  {
    id: '1',
    name: 'Swan Oyster Depot',
    description: 'Historic seafood counter serving fresh oysters, clam chowder, and crab since 1912. A true San Francisco institution.',
    type: 'food',
    neighborhood: 'Nob Hill',
    address: '1517 Polk St, San Francisco, CA 94109',
    lat: 37.7897,
    lng: -122.4204,
    priceLevel: 2,
    timeOfDay: 'afternoon',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: false,
    imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
    duration: 60,
    rating: 4.8,
  },
  {
    id: '2',
    name: 'Golden Gate Bridge Walk',
    description: 'Stroll across the iconic Golden Gate Bridge with stunning views of the bay, Alcatraz, and the city skyline.',
    type: 'sightseeing',
    neighborhood: 'Presidio',
    address: 'Golden Gate Bridge, San Francisco, CA',
    lat: 37.8199,
    lng: -122.4783,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1539667468225-eebb663053e6?w=800',
    duration: 90,
    rating: 4.9,
  },
  {
    id: '3',
    name: 'SFMOMA',
    description: 'San Francisco Museum of Modern Art featuring contemporary works and rotating exhibitions in a stunning architectural space.',
    type: 'arts',
    neighborhood: 'SoMa',
    address: '151 3rd St, San Francisco, CA 94103',
    lat: 37.7858,
    lng: -122.4011,
    priceLevel: 3,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
    duration: 180,
    rating: 4.7,
    bookingUrl: 'https://www.sfmoma.org/visit/',
  },
  {
    id: '4',
    name: 'Ferry Building Marketplace',
    description: 'Historic ferry terminal turned gourmet marketplace with artisan food vendors, farmers market, and bay views.',
    type: 'food',
    neighborhood: 'Embarcadero',
    address: '1 Ferry Building, San Francisco, CA 94111',
    lat: 37.7955,
    lng: -122.3933,
    priceLevel: 2,
    timeOfDay: 'morning',
    indoor: true,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800',
    duration: 120,
    rating: 4.6,
  },
  {
    id: '5',
    name: 'Tartine Manufactory',
    description: 'Modern bakery and restaurant serving artisanal bread, pastries, and seasonal California cuisine in a bright, airy space.',
    type: 'food',
    neighborhood: 'Mission District',
    address: '595 Alabama St, San Francisco, CA 94110',
    lat: 37.7634,
    lng: -122.4105,
    priceLevel: 3,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
    duration: 90,
    rating: 4.5,
  },
  {
    id: '6',
    name: 'Lands End Trail',
    description: 'Scenic coastal trail with dramatic ocean views, the ruins of Sutro Baths, and hidden beaches. Perfect for sunset walks.',
    type: 'outdoor',
    neighborhood: 'Richmond',
    address: 'Lands End, San Francisco, CA 94121',
    lat: 37.7838,
    lng: -122.5076,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: false,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    duration: 120,
    rating: 4.8,
  },
  {
    id: '7',
    name: 'The View Lounge',
    description: 'Sophisticated rooftop lounge with panoramic city views, craft cocktails, and small plates. Perfect for special occasions.',
    type: 'nightlife',
    neighborhood: 'Financial District',
    address: '780 Mission St, San Francisco, CA 94103',
    lat: 37.7849,
    lng: -122.4094,
    priceLevel: 3,
    timeOfDay: 'evening',
    indoor: true,
    outdoor: true,
    kidFriendly: false,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
    duration: 120,
    rating: 4.6,
  },
  {
    id: '8',
    name: 'Palace of Fine Arts',
    description: 'Stunning Greco-Roman inspired structure surrounded by peaceful lagoon and gardens. A serene spot for reflection and photos.',
    type: 'sightseeing',
    neighborhood: 'Marina',
    address: '3601 Lyon St, San Francisco, CA 94123',
    lat: 37.8024,
    lng: -122.4488,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800',
    duration: 60,
    rating: 4.7,
  },
  {
    id: '9',
    name: 'Tartine Bakery',
    description: 'Iconic Mission bakery known for its morning bun and rustic country bread. A must-visit for pastry lovers.',
    type: 'food',
    neighborhood: 'Mission District',
    address: '600 Guerrero St, San Francisco, CA 94110',
    lat: 37.7627,
    lng: -122.4247,
    priceLevel: 2,
    timeOfDay: 'morning',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: false,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
    duration: 45,
    rating: 4.5,
  },
  {
    id: '10',
    name: 'Alcatraz Island Tour',
    description: 'Boat tour to the infamous former prison island. Includes audio tour and stunning views of the city from the bay.',
    type: 'sightseeing',
    neighborhood: 'Fisherman\'s Wharf',
    address: 'Pier 33, San Francisco, CA 94111',
    lat: 37.8070,
    lng: -122.4183,
    priceLevel: 3,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1544866092-1935c0eef97e?w=800',
    duration: 240,
    rating: 4.6,
    bookingUrl: 'https://www.alcatrazcruises.com/',
  },
  {
    id: '11',
    name: 'Yerba Buena Gardens',
    description: 'Peaceful urban park with modern sculptures, fountains, and plenty of green space. Ideal for quiet moments or family picnics.',
    type: 'outdoor',
    neighborhood: 'SoMa',
    address: '750 Mission St, San Francisco, CA 94103',
    lat: 37.7849,
    lng: -122.4024,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
    duration: 60,
    rating: 4.4,
  },
  {
    id: '12',
    name: 'The Interval at Long Now',
    description: 'Thoughtful café and bar in Fort Mason featuring craft cocktails, coffee, and books. A quiet space for reflection.',
    type: 'nightlife',
    neighborhood: 'Marina',
    address: '2 Marina Blvd, Fort Mason, San Francisco, CA 94123',
    lat: 37.8064,
    lng: -122.4321,
    priceLevel: 2,
    timeOfDay: 'evening',
    indoor: true,
    outdoor: false,
    kidFriendly: false,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    duration: 90,
    rating: 4.6,
  },
  {
    id: '13',
    name: 'Mission Dolores Park',
    description: 'Iconic hillside park with stunning city views, perfect for picnics, sunbathing, and people-watching.',
    type: 'outdoor',
    neighborhood: 'Mission District',
    address: 'Dolores St & 19th St, San Francisco, CA 94114',
    lat: 37.7597,
    lng: -122.4270,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
    duration: 120,
    rating: 4.7,
  },
  {
    id: '14',
    name: 'Coit Tower',
    description: 'Historic Art Deco tower offering panoramic 360-degree views of San Francisco. Accessible by elevator or stairs.',
    type: 'sightseeing',
    neighborhood: 'Telegraph Hill',
    address: '1 Telegraph Hill Blvd, San Francisco, CA 94133',
    lat: 37.8024,
    lng: -122.4058,
    priceLevel: 2,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1555993538-89e9c1b0e16a?w=800',
    duration: 60,
    rating: 4.5,
  },
  {
    id: '15',
    name: 'Blue Bottle Coffee',
    description: 'Artisanal coffee roaster known for its meticulously crafted pour-overs and espresso. Perfect for coffee connoisseurs.',
    type: 'food',
    neighborhood: 'Hayes Valley',
    address: '315 Linden St, San Francisco, CA 94102',
    lat: 37.7749,
    lng: -122.4194,
    priceLevel: 2,
    timeOfDay: 'morning',
    indoor: true,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
    duration: 45,
    rating: 4.4,
  },
  {
    id: '16',
    name: 'Gary Danko',
    description: 'Upscale French-American fine dining restaurant with exquisite tasting menus. Perfect for special celebrations and romantic dinners.',
    type: 'food',
    neighborhood: 'Fisherman\'s Wharf',
    address: '800 North Point St, San Francisco, CA 94109',
    lat: 37.8064,
    lng: -122.4189,
    priceLevel: 4,
    timeOfDay: 'evening',
    indoor: true,
    outdoor: false,
    kidFriendly: false,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
    duration: 180,
    rating: 4.8,
    bookingUrl: 'https://www.garydanko.com/',
  },
  {
    id: '17',
    name: 'Swan Oyster Depot',
    description: 'Historic seafood counter serving fresh oysters, clam chowder, and crab since 1912. A true San Francisco institution.',
    type: 'food',
    neighborhood: 'Nob Hill',
    address: '1517 Polk St, San Francisco, CA 94109',
    lat: 37.7897,
    lng: -122.4204,
    priceLevel: 2,
    timeOfDay: 'lunch',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: false,
    imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
    duration: 60,
    rating: 4.8,
  },
  {
    id: '18',
    name: 'Crissy Field',
    description: 'Beautiful waterfront park with Golden Gate Bridge views. Perfect for family picnics, walks, and kite flying.',
    type: 'outdoor',
    neighborhood: 'Marina',
    address: '1199 East Beach, San Francisco, CA 94129',
    lat: 37.8024,
    lng: -122.4488,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1539667468225-eebb663053e6?w=800',
    duration: 120,
    rating: 4.7,
  },
  {
    id: '19',
    name: 'Japanese Tea Garden',
    description: 'Peaceful traditional Japanese garden in Golden Gate Park. A serene spot for quiet reflection and beautiful photos.',
    type: 'outdoor',
    neighborhood: 'Golden Gate Park',
    address: '75 Hagiwara Tea Garden Dr, San Francisco, CA 94118',
    lat: 37.7694,
    lng: -122.4708,
    priceLevel: 2,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800',
    duration: 90,
    rating: 4.6,
  },
  {
    id: '20',
    name: 'The Presidio',
    description: 'Historic former military base turned national park with hiking trails, museums, and stunning Bay views.',
    type: 'outdoor',
    neighborhood: 'Presidio',
    address: 'Presidio of San Francisco, CA 94129',
    lat: 37.8001,
    lng: -122.4644,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    duration: 180,
    rating: 4.8,
  },
  {
    id: '21',
    name: 'Waterfront Restaurant',
    description: 'Elegant waterfront dining with panoramic Bay views and fresh seafood. Ideal for romantic dinners and special occasions.',
    type: 'food',
    neighborhood: 'Fisherman\'s Wharf',
    address: 'Pier 39, San Francisco, CA 94133',
    lat: 37.8087,
    lng: -122.4098,
    priceLevel: 3,
    timeOfDay: 'evening',
    indoor: true,
    outdoor: true,
    kidFriendly: false,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    duration: 120,
    rating: 4.5,
  },
  {
    id: '22',
    name: 'Golden Gate Park Carousel',
    description: 'Historic carousel perfect for family outings. Children love the hand-carved animals and classic music.',
    type: 'family',
    neighborhood: 'Golden Gate Park',
    address: 'Music Concourse Dr, San Francisco, CA 94117',
    lat: 37.7694,
    lng: -122.4676,
    priceLevel: 1,
    timeOfDay: 'afternoon',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800',
    duration: 30,
    rating: 4.5,
  },
  {
    id: '23',
    name: 'Cable Car Museum',
    description: 'Free museum showcasing San Francisco\'s iconic cable car system. Great for families and history buffs.',
    type: 'arts',
    neighborhood: 'Nob Hill',
    address: '1201 Mason St, San Francisco, CA 94108',
    lat: 37.7949,
    lng: -122.4115,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
    duration: 60,
    rating: 4.4,
  },
  {
    id: '24',
    name: 'Baker Beach',
    description: 'Stunning beach with iconic Golden Gate Bridge views. Perfect for sunset watching and peaceful walks.',
    type: 'outdoor',
    category: 'outdoor',
    neighborhood: 'Presidio',
    address: 'Battery Chamberlain Rd, San Francisco, CA 94129',
    lat: 37.7936,
    lng: -122.4832,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: false,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    duration: 90,
    rating: 4.7,
    highlights: ['Sunset views', 'Beach access', 'Golden Gate Bridge views'],
  },
  // Activities
  {
    id: '25',
    name: 'Emporium Arcade Bar',
    description: 'Retro arcade bar with classic games, pinball machines, and craft cocktails. Perfect for a fun night out with friends.',
    type: 'activities',
    category: 'activities',
    neighborhood: 'Mission District',
    address: '616 Divisadero St, San Francisco, CA 94117',
    lat: 37.7749,
    lng: -122.4376,
    priceLevel: 2,
    timeOfDay: 'evening',
    indoor: true,
    outdoor: false,
    kidFriendly: false,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800',
    duration: 120,
    rating: 4.6,
    hours: 'Mon-Thu: 5pm-2am, Fri-Sun: 12pm-2am',
    highlights: ['Classic arcade games', 'Pinball machines', 'Craft cocktails'],
  },
  {
    id: '26',
    name: 'Mission Bowling Club',
    description: 'Upscale bowling alley with 6 lanes, full bar, and restaurant. Great for group celebrations and date nights.',
    type: 'activities',
    category: 'activities',
    neighborhood: 'Mission District',
    address: '3176 17th St, San Francisco, CA 94110',
    lat: 37.7634,
    lng: -122.4205,
    priceLevel: 2,
    timeOfDay: 'evening',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800',
    duration: 120,
    rating: 4.5,
    hours: 'Mon-Thu: 5pm-12am, Fri-Sat: 5pm-2am, Sun: 12pm-12am',
    highlights: ['6 bowling lanes', 'Full bar', 'Restaurant'],
  },
  {
    id: '27',
    name: 'Palace Games Escape Room',
    description: 'Immersive escape room experiences with intricate puzzles and themed adventures. Perfect for team building and fun challenges.',
    type: 'activities',
    category: 'activities',
    neighborhood: 'Financial District',
    address: '490 Geary St, San Francisco, CA 94102',
    lat: 37.7874,
    lng: -122.4094,
    priceLevel: 3,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: false,
    kidFriendly: false,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    duration: 60,
    rating: 4.8,
    hours: 'Daily: 10am-10pm',
    highlights: ['Themed rooms', 'Team challenges', 'Immersive puzzles'],
    bookingUrl: 'https://palacegames.com/',
  },
  {
    id: '28',
    name: 'Lucky Strike Karaoke',
    description: 'Private karaoke rooms with thousands of songs, full bar service, and late-night hours. Perfect for birthday celebrations.',
    type: 'activities',
    category: 'activities',
    neighborhood: 'SoMa',
    address: '200 3rd St, San Francisco, CA 94103',
    lat: 37.7858,
    lng: -122.4011,
    priceLevel: 2,
    timeOfDay: 'evening',
    indoor: true,
    outdoor: false,
    kidFriendly: false,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    duration: 120,
    rating: 4.4,
    hours: 'Daily: 6pm-2am',
    highlights: ['Private rooms', 'Thousands of songs', 'Full bar'],
  },
  // Entertainment
  {
    id: '29',
    name: 'Alamo Drafthouse Cinema',
    description: 'Premium movie theater with full-service dining, craft cocktails, and the latest blockbusters. Perfect for date nights.',
    type: 'entertainment',
    category: 'entertainment',
    neighborhood: 'Mission District',
    address: '2550 Mission St, San Francisco, CA 94110',
    lat: 37.7556,
    lng: -122.4194,
    priceLevel: 2,
    timeOfDay: 'evening',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800',
    duration: 150,
    rating: 4.7,
    hours: 'Daily: 11am-11pm',
    highlights: ['Full-service dining', 'Craft cocktails', 'Latest releases'],
    bookingUrl: 'https://drafthouse.com/',
  },
  {
    id: '30',
    name: 'The Fillmore',
    description: 'Historic music venue hosting legendary concerts since 1965. Intimate setting with incredible acoustics and atmosphere.',
    type: 'entertainment',
    category: 'entertainment',
    neighborhood: 'Western Addition',
    address: '1805 Geary Blvd, San Francisco, CA 94115',
    lat: 37.7841,
    lng: -122.4331,
    priceLevel: 2,
    timeOfDay: 'evening',
    indoor: true,
    outdoor: false,
    kidFriendly: false,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
    duration: 180,
    rating: 4.8,
    hours: 'Varies by show',
    highlights: ['Historic venue', 'Live music', 'Great acoustics'],
    bookingUrl: 'https://thefillmore.com/',
  },
  {
    id: '31',
    name: 'Cobb\'s Comedy Club',
    description: 'Premier comedy club featuring top stand-up comedians and open mic nights. Laugh your way through the evening.',
    type: 'entertainment',
    category: 'entertainment',
    neighborhood: 'North Beach',
    address: '915 Columbus Ave, San Francisco, CA 94133',
    lat: 37.8054,
    lng: -122.4108,
    priceLevel: 2,
    timeOfDay: 'evening',
    indoor: true,
    outdoor: false,
    kidFriendly: false,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800',
    duration: 90,
    rating: 4.5,
    hours: 'Tue-Sun: 8pm-11pm',
    highlights: ['Top comedians', 'Open mic nights', 'Full bar'],
    bookingUrl: 'https://cobbscomedy.com/',
  },
  // Cultural
  {
    id: '32',
    name: 'de Young Museum',
    description: 'Fine arts museum in Golden Gate Park featuring American art, international contemporary art, and rotating exhibitions.',
    type: 'cultural',
    category: 'cultural',
    neighborhood: 'Golden Gate Park',
    address: '50 Hagiwara Tea Garden Dr, San Francisco, CA 94118',
    lat: 37.7849,
    lng: -122.4686,
    priceLevel: 2,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
    duration: 180,
    rating: 4.7,
    hours: 'Tue-Sun: 9:30am-5:15pm',
    highlights: ['American art', 'Contemporary exhibitions', 'Observation deck'],
    bookingUrl: 'https://deyoung.famsf.org/',
  },
  {
    id: '33',
    name: 'Asian Art Museum',
    description: 'One of the largest museums in the Western world devoted exclusively to Asian art and culture.',
    type: 'cultural',
    category: 'cultural',
    neighborhood: 'Civic Center',
    address: '200 Larkin St, San Francisco, CA 94102',
    lat: 37.7804,
    lng: -122.4168,
    priceLevel: 2,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
    duration: 150,
    rating: 4.6,
    hours: 'Tue-Sun: 10am-5pm',
    highlights: ['Asian art collection', 'Cultural exhibitions', 'Family programs'],
    bookingUrl: 'https://asianart.org/',
  },
  {
    id: '34',
    name: 'Cable Car Museum',
    description: 'Free museum showcasing San Francisco\'s iconic cable car system. Great for families and history buffs.',
    type: 'cultural',
    category: 'cultural',
    neighborhood: 'Nob Hill',
    address: '1201 Mason St, San Francisco, CA 94108',
    lat: 37.7949,
    lng: -122.4115,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
    duration: 60,
    rating: 4.4,
    hours: 'Daily: 10am-5pm',
    highlights: ['Free admission', 'Historic cable cars', 'Working machinery'],
  },
  // Free Activities
  {
    id: '35',
    name: 'Stern Grove Festival',
    description: 'Free outdoor summer concert series in a beautiful eucalyptus grove. Bring a blanket and enjoy live music.',
    type: 'free',
    category: 'free',
    neighborhood: 'Sunset',
    address: '19th Ave & Sloat Blvd, San Francisco, CA 94132',
    lat: 37.7374,
    lng: -122.4832,
    priceLevel: 1,
    timeOfDay: 'afternoon',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
    duration: 120,
    rating: 4.8,
    hours: 'Sundays: 2pm-5pm (Summer)',
    highlights: ['Free concerts', 'Outdoor setting', 'Family-friendly'],
  },
  {
    id: '36',
    name: 'Ferry Plaza Farmers Market',
    description: 'Free farmers market every Tuesday and Saturday with local produce, artisan foods, and live music.',
    type: 'free',
    category: 'free',
    neighborhood: 'Embarcadero',
    address: '1 Ferry Building, San Francisco, CA 94111',
    lat: 37.7955,
    lng: -122.3933,
    priceLevel: 1,
    timeOfDay: 'morning',
    indoor: true,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800',
    duration: 90,
    rating: 4.7,
    hours: 'Tue & Sat: 10am-2pm',
    highlights: ['Local produce', 'Artisan foods', 'Free to browse'],
  },
  {
    id: '37',
    name: 'Lombard Street Walk',
    description: 'Free scenic walk down the "crookedest street in the world" with beautiful gardens and city views.',
    type: 'free',
    category: 'free',
    neighborhood: 'Russian Hill',
    address: 'Lombard St, San Francisco, CA 94133',
    lat: 37.8021,
    lng: -122.4186,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: false,
    imageUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800',
    duration: 30,
    rating: 4.6,
    hours: 'Always open',
    highlights: ['Iconic street', 'Beautiful gardens', 'City views'],
  },
  {
    id: '38',
    name: 'Twin Peaks',
    description: 'Free panoramic viewpoint offering 360-degree views of San Francisco. Best visited at sunset or sunrise.',
    type: 'free',
    category: 'free',
    neighborhood: 'Twin Peaks',
    address: 'Twin Peaks Blvd, San Francisco, CA 94114',
    lat: 37.7516,
    lng: -122.4475,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800',
    duration: 45,
    rating: 4.9,
    hours: 'Always open',
    highlights: ['360-degree views', 'Sunset spot', 'Free parking'],
  },
  // Shopping
  {
    id: '39',
    name: 'City Lights Booksellers',
    description: 'Historic independent bookstore and publisher, famous for Beat Generation literature. A literary landmark.',
    type: 'shopping',
    category: 'shopping',
    neighborhood: 'North Beach',
    address: '261 Columbus Ave, San Francisco, CA 94133',
    lat: 37.7979,
    lng: -122.4067,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
    duration: 60,
    rating: 4.8,
    hours: 'Daily: 10am-10pm',
    highlights: ['Historic bookstore', 'Beat Generation', 'Literary events'],
  },
  {
    id: '40',
    name: 'Heath Ceramics',
    description: 'Beautiful ceramics and home goods made in Sausalito. Showroom features handcrafted dinnerware and decor.',
    type: 'shopping',
    category: 'shopping',
    neighborhood: 'Mission District',
    address: '2900 18th St, San Francisco, CA 94110',
    lat: 37.7634,
    lng: -122.4105,
    priceLevel: 3,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
    duration: 45,
    rating: 4.6,
    hours: 'Mon-Sat: 10am-6pm, Sun: 11am-5pm',
    highlights: ['Handcrafted ceramics', 'Home goods', 'Made in California'],
  },
  {
    id: '41',
    name: 'The Ferry Building Shops',
    description: 'Curated collection of artisan shops, specialty foods, and unique gifts. Perfect for finding something special.',
    type: 'shopping',
    category: 'shopping',
    neighborhood: 'Embarcadero',
    address: '1 Ferry Building, San Francisco, CA 94111',
    lat: 37.7955,
    lng: -122.3933,
    priceLevel: 2,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800',
    duration: 90,
    rating: 4.5,
    hours: 'Daily: 10am-6pm',
    highlights: ['Artisan shops', 'Specialty foods', 'Unique gifts'],
  },
];

