import { Experience } from './store';

export const mockExperiences: Experience[] = [
  {
    id: '1',
    name: 'Swan Oyster Depot',
    description: 'Historic seafood counter serving fresh oysters, clam chowder, and crab since 1912. A true San Francisco institution.',
    type: 'food',
    neighborhood: 'Nob Hill',
    address: '1517 Polk St, San Francisco, CA 94109',
    lat: 37.7897,
    lng: -122.4204,
    priceLevel: 2,
    timeOfDay: 'afternoon',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: false,
    imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
    duration: 60,
    rating: 4.8,
  },
  {
    id: '2',
    name: 'Golden Gate Bridge Walk',
    description: 'Stroll across the iconic Golden Gate Bridge with stunning views of the bay, Alcatraz, and the city skyline.',
    type: 'sightseeing',
    neighborhood: 'Presidio',
    address: 'Golden Gate Bridge, San Francisco, CA',
    lat: 37.8199,
    lng: -122.4783,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1539667468225-eebb663053e6?w=800',
    duration: 90,
    rating: 4.9,
  },
  {
    id: '3',
    name: 'SFMOMA',
    description: 'San Francisco Museum of Modern Art featuring contemporary works and rotating exhibitions in a stunning architectural space.',
    type: 'arts',
    neighborhood: 'SoMa',
    address: '151 3rd St, San Francisco, CA 94103',
    lat: 37.7858,
    lng: -122.4011,
    priceLevel: 3,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
    duration: 180,
    rating: 4.7,
    bookingUrl: 'https://www.sfmoma.org/visit/',
  },
  {
    id: '4',
    name: 'Ferry Building Marketplace',
    description: 'Historic ferry terminal turned gourmet marketplace with artisan food vendors, farmers market, and bay views.',
    type: 'food',
    neighborhood: 'Embarcadero',
    address: '1 Ferry Building, San Francisco, CA 94111',
    lat: 37.7955,
    lng: -122.3933,
    priceLevel: 2,
    timeOfDay: 'morning',
    indoor: true,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800',
    duration: 120,
    rating: 4.6,
  },
  {
    id: '5',
    name: 'Tartine Manufactory',
    description: 'Modern bakery and restaurant serving artisanal bread, pastries, and seasonal California cuisine in a bright, airy space.',
    type: 'food',
    neighborhood: 'Mission District',
    address: '595 Alabama St, San Francisco, CA 94110',
    lat: 37.7634,
    lng: -122.4105,
    priceLevel: 3,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
    duration: 90,
    rating: 4.5,
  },
  {
    id: '6',
    name: 'Lands End Trail',
    description: 'Scenic coastal trail with dramatic ocean views, the ruins of Sutro Baths, and hidden beaches. Perfect for sunset walks.',
    type: 'outdoor',
    neighborhood: 'Richmond',
    address: 'Lands End, San Francisco, CA 94121',
    lat: 37.7838,
    lng: -122.5076,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: false,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    duration: 120,
    rating: 4.8,
  },
  {
    id: '7',
    name: 'The View Lounge',
    description: 'Sophisticated rooftop lounge with panoramic city views, craft cocktails, and small plates. Perfect for special occasions.',
    type: 'nightlife',
    neighborhood: 'Financial District',
    address: '780 Mission St, San Francisco, CA 94103',
    lat: 37.7849,
    lng: -122.4094,
    priceLevel: 3,
    timeOfDay: 'evening',
    indoor: true,
    outdoor: true,
    kidFriendly: false,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
    duration: 120,
    rating: 4.6,
  },
  {
    id: '8',
    name: 'Palace of Fine Arts',
    description: 'Stunning Greco-Roman inspired structure surrounded by peaceful lagoon and gardens. A serene spot for reflection and photos.',
    type: 'sightseeing',
    neighborhood: 'Marina',
    address: '3601 Lyon St, San Francisco, CA 94123',
    lat: 37.8024,
    lng: -122.4488,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800',
    duration: 60,
    rating: 4.7,
  },
  {
    id: '9',
    name: 'Tartine Bakery',
    description: 'Iconic Mission bakery known for its morning bun and rustic country bread. A must-visit for pastry lovers.',
    type: 'food',
    neighborhood: 'Mission District',
    address: '600 Guerrero St, San Francisco, CA 94110',
    lat: 37.7627,
    lng: -122.4247,
    priceLevel: 2,
    timeOfDay: 'morning',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: false,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
    duration: 45,
    rating: 4.5,
  },
  {
    id: '10',
    name: 'Alcatraz Island Tour',
    description: 'Boat tour to the infamous former prison island. Includes audio tour and stunning views of the city from the bay.',
    type: 'sightseeing',
    neighborhood: 'Fisherman\'s Wharf',
    address: 'Pier 33, San Francisco, CA 94111',
    lat: 37.8070,
    lng: -122.4183,
    priceLevel: 3,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1544866092-1935c0eef97e?w=800',
    duration: 240,
    rating: 4.6,
    bookingUrl: 'https://www.alcatrazcruises.com/',
  },
  {
    id: '11',
    name: 'Yerba Buena Gardens',
    description: 'Peaceful urban park with modern sculptures, fountains, and plenty of green space. Ideal for quiet moments or family picnics.',
    type: 'outdoor',
    neighborhood: 'SoMa',
    address: '750 Mission St, San Francisco, CA 94103',
    lat: 37.7849,
    lng: -122.4024,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
    duration: 60,
    rating: 4.4,
  },
  {
    id: '12',
    name: 'The Interval at Long Now',
    description: 'Thoughtful café and bar in Fort Mason featuring craft cocktails, coffee, and books. A quiet space for reflection.',
    type: 'nightlife',
    neighborhood: 'Marina',
    address: '2 Marina Blvd, Fort Mason, San Francisco, CA 94123',
    lat: 37.8064,
    lng: -122.4321,
    priceLevel: 2,
    timeOfDay: 'evening',
    indoor: true,
    outdoor: false,
    kidFriendly: false,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    duration: 90,
    rating: 4.6,
  },
  {
    id: '13',
    name: 'Mission Dolores Park',
    description: 'Iconic hillside park with stunning city views, perfect for picnics, sunbathing, and people-watching.',
    type: 'outdoor',
    neighborhood: 'Mission District',
    address: 'Dolores St & 19th St, San Francisco, CA 94114',
    lat: 37.7597,
    lng: -122.4270,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
    duration: 120,
    rating: 4.7,
  },
  {
    id: '14',
    name: 'Coit Tower',
    description: 'Historic Art Deco tower offering panoramic 360-degree views of San Francisco. Accessible by elevator or stairs.',
    type: 'sightseeing',
    neighborhood: 'Telegraph Hill',
    address: '1 Telegraph Hill Blvd, San Francisco, CA 94133',
    lat: 37.8024,
    lng: -122.4058,
    priceLevel: 2,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1555993538-89e9c1b0e16a?w=800',
    duration: 60,
    rating: 4.5,
  },
  {
    id: '15',
    name: 'Blue Bottle Coffee',
    description: 'Artisanal coffee roaster known for its meticulously crafted pour-overs and espresso. Perfect for coffee connoisseurs.',
    type: 'food',
    neighborhood: 'Hayes Valley',
    address: '315 Linden St, San Francisco, CA 94102',
    lat: 37.7749,
    lng: -122.4194,
    priceLevel: 2,
    timeOfDay: 'morning',
    indoor: true,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
    duration: 45,
    rating: 4.4,
  },
  {
    id: '16',
    name: 'Gary Danko',
    description: 'Upscale French-American fine dining restaurant with exquisite tasting menus. Perfect for special celebrations and romantic dinners.',
    type: 'food',
    neighborhood: 'Fisherman\'s Wharf',
    address: '800 North Point St, San Francisco, CA 94109',
    lat: 37.8064,
    lng: -122.4189,
    priceLevel: 4,
    timeOfDay: 'evening',
    indoor: true,
    outdoor: false,
    kidFriendly: false,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
    duration: 180,
    rating: 4.8,
    bookingUrl: 'https://www.garydanko.com/',
  },
  {
    id: '17',
    name: 'Swan Oyster Depot',
    description: 'Historic seafood counter serving fresh oysters, clam chowder, and crab since 1912. A true San Francisco institution.',
    type: 'food',
    neighborhood: 'Nob Hill',
    address: '1517 Polk St, San Francisco, CA 94109',
    lat: 37.7897,
    lng: -122.4204,
    priceLevel: 2,
    timeOfDay: 'lunch',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: false,
    imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
    duration: 60,
    rating: 4.8,
  },
  {
    id: '18',
    name: 'Crissy Field',
    description: 'Beautiful waterfront park with Golden Gate Bridge views. Perfect for family picnics, walks, and kite flying.',
    type: 'outdoor',
    neighborhood: 'Marina',
    address: '1199 East Beach, San Francisco, CA 94129',
    lat: 37.8024,
    lng: -122.4488,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1539667468225-eebb663053e6?w=800',
    duration: 120,
    rating: 4.7,
  },
  {
    id: '19',
    name: 'Japanese Tea Garden',
    description: 'Peaceful traditional Japanese garden in Golden Gate Park. A serene spot for quiet reflection and beautiful photos.',
    type: 'outdoor',
    neighborhood: 'Golden Gate Park',
    address: '75 Hagiwara Tea Garden Dr, San Francisco, CA 94118',
    lat: 37.7694,
    lng: -122.4708,
    priceLevel: 2,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800',
    duration: 90,
    rating: 4.6,
  },
  {
    id: '20',
    name: 'The Presidio',
    description: 'Historic former military base turned national park with hiking trails, museums, and stunning Bay views.',
    type: 'outdoor',
    neighborhood: 'Presidio',
    address: 'Presidio of San Francisco, CA 94129',
    lat: 37.8001,
    lng: -122.4644,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    duration: 180,
    rating: 4.8,
  },
  {
    id: '21',
    name: 'Waterfront Restaurant',
    description: 'Elegant waterfront dining with panoramic Bay views and fresh seafood. Ideal for romantic dinners and special occasions.',
    type: 'food',
    neighborhood: 'Fisherman\'s Wharf',
    address: 'Pier 39, San Francisco, CA 94133',
    lat: 37.8087,
    lng: -122.4098,
    priceLevel: 3,
    timeOfDay: 'evening',
    indoor: true,
    outdoor: true,
    kidFriendly: false,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    duration: 120,
    rating: 4.5,
  },
  {
    id: '22',
    name: 'Golden Gate Park Carousel',
    description: 'Historic carousel perfect for family outings. Children love the hand-carved animals and classic music.',
    type: 'family',
    neighborhood: 'Golden Gate Park',
    address: 'Music Concourse Dr, San Francisco, CA 94117',
    lat: 37.7694,
    lng: -122.4676,
    priceLevel: 1,
    timeOfDay: 'afternoon',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800',
    duration: 30,
    rating: 4.5,
  },
  {
    id: '23',
    name: 'Cable Car Museum',
    description: 'Free museum showcasing San Francisco\'s iconic cable car system. Great for families and history buffs.',
    type: 'arts',
    neighborhood: 'Nob Hill',
    address: '1201 Mason St, San Francisco, CA 94108',
    lat: 37.7949,
    lng: -122.4115,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: true,
    outdoor: false,
    kidFriendly: true,
    accessibility: true,
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
    duration: 60,
    rating: 4.4,
  },
  {
    id: '24',
    name: 'Baker Beach',
    description: 'Stunning beach with iconic Golden Gate Bridge views. Perfect for sunset watching and peaceful walks.',
    type: 'outdoor',
    neighborhood: 'Presidio',
    address: 'Battery Chamberlain Rd, San Francisco, CA 94129',
    lat: 37.7936,
    lng: -122.4832,
    priceLevel: 1,
    timeOfDay: 'anytime',
    indoor: false,
    outdoor: true,
    kidFriendly: true,
    accessibility: false,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    duration: 90,
    rating: 4.7,
  },
];

